[project]
name = "gen-ai-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "huggingface-hub>=0.33.4",
    "ipykernel>=6.29.5",
    "langchain>=0.3.26",
    "langchain-community>=0.3.27",
    "langchain-groq>=0.3.6",
    "langchain-huggingface>=0.3.1",
    "langchain-openai>=0.3.28",
    "langchain-text-spliter",
    "langgraph>=0.5.3",
    "lxml-html-clean>=0.4.2",
    "notebook>=7.4.4",
    "openai>=1.97.0",
    "pandas>=2.3.1",
    "pypdf>=5.8.0",
    "python-dotenv>=1.1.1",
    "requests-html>=0.10.0",
    "tensorflow>=2.20.0",
    "transformers>=4.53.2",
]
